/**
 * Lazy loader for the imported Workshop ACC setup library.
 *
 * Data lives in static files under /data/imported/workshop-acc/ (generated by
 * scripts/import-workshop-acc.ts). Nothing is bundled: the small manifest is fetched
 * when the library opens, and each car's file only when that car is selected.
 *
 * To remove the import entirely: delete public/data/imported/workshop-acc/ and the
 * "IMPORTED" registry tab in App.tsx.
 */
import { fetchWithRetry } from "../utils/fetchWithRetry";
import {
  WORKSHOP_SLOTS,
  type DecodedField,
  type DecodedValue,
  type ImportedCarFile,
  type ImportedCarIndexEntry,
  type ImportedFieldLayout,
  type ImportedManifest,
  type ImportedSetupRow,
  type WorkshopSlot,
} from "../types/workshopAcc";

const BASE_URL = "/data/imported/workshop-acc";

let manifestPromise: Promise<ImportedManifest> | null = null;
const carCache = new Map<string, Promise<ImportedCarFile>>();

function isRecord(x: unknown): x is Record<string, unknown> {
  return typeof x === "object" && x !== null && !Array.isArray(x);
}

function isManifest(x: unknown): x is ImportedManifest {
  return isRecord(x) && isRecord(x.source) && Array.isArray(x.cars) && Array.isArray(x.tracks) && Array.isArray(x.layout);
}

function isCarFile(x: unknown): x is ImportedCarFile {
  return isRecord(x) && typeof x.appId === "string" && Array.isArray(x.setups) && Array.isArray(x.status);
}

async function fetchJson<T>(url: string, guard: (x: unknown) => x is T): Promise<T> {
  return fetchWithRetry(async () => {
    const res = await fetch(url);
    if (!res.ok) throw new Error(`Failed to load ${url} (${res.status})`);
    const body: unknown = await res.json();
    if (!guard(body)) throw new Error(`Unexpected data format in ${url}`);
    return body;
  }, 2, 500);
}

export function loadImportedManifest(): Promise<ImportedManifest> {
  if (!manifestPromise) {
    manifestPromise = fetchJson(`${BASE_URL}/manifest.json`, isManifest).catch((err: unknown) => {
      manifestPromise = null; // allow retry on next call
      throw err;
    });
  }
  return manifestPromise;
}

export function loadImportedCar(entry: ImportedCarIndexEntry): Promise<ImportedCarFile> {
  let p = carCache.get(entry.appId);
  if (!p) {
    p = fetchJson(`${BASE_URL}/${entry.file}`, isCarFile).catch((err: unknown) => {
      carCache.delete(entry.appId);
      throw err;
    });
    carCache.set(entry.appId, p);
  }
  return p;
}

/** Slots available for a car at a track, in canonical order. */
export function slotsFor(entry: ImportedCarIndexEntry | undefined, trackId: string): WorkshopSlot[] {
  const mask = entry?.slotMask[trackId] ?? 0;
  return WORKSHOP_SLOTS.filter((_, i) => (mask & (1 << i)) !== 0);
}

export function findImportedSetup(car: ImportedCarFile, trackId: string, slot: WorkshopSlot): ImportedSetupRow | undefined {
  return car.setups.find((s) => s.track === trackId && s.slot === slot);
}

/** Re-expands a compact stored row into per-field decoded values for display. */
export function expandImportedSetup(car: ImportedCarFile, layout: readonly ImportedFieldLayout[], row: ImportedSetupRow): DecodedField[] {
  return layout.map(({ path, width, offset, unit }) => ({
    path,
    values: Array.from({ length: width }, (_, slot): DecodedValue => {
      const i = offset + slot;
      const override = row.overrides?.[i];
      const status = override?.status ?? car.status[i] ?? "raw";
      const note = override?.note ?? car.notes[i];
      const base: DecodedValue = { click: row.clicks[i] ?? Number.NaN, value: row.values[i] ?? null, unit: status === "index-only" ? "" : unit, status };
      return note ? { ...base, note } : base;
    }),
  }));
}
